package ch.so.agi.datahub.cayenne.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;

import ch.so.agi.datahub.cayenne.CoreOperat;
import ch.so.agi.datahub.cayenne.CoreOrganisationUser;

/**
 * Class _CoreOrganisation was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CoreOrganisation extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String T_ID_PK_COLUMN = "t_id";

    public static final StringProperty<String> ANAME = PropertyFactory.createString("aname", String.class);
    public static final StringProperty<String> AUID = PropertyFactory.createString("auid", String.class);
    public static final ListProperty<CoreOperat> CORE_OPERATS = PropertyFactory.createList("coreOperats", CoreOperat.class);
    public static final ListProperty<CoreOrganisationUser> CORE_ORGANISATION_USERS = PropertyFactory.createList("coreOrganisationUsers", CoreOrganisationUser.class);

    protected String aname;
    protected String auid;

    protected Object coreOperats;
    protected Object coreOrganisationUsers;

    public void setAname(String aname) {
        beforePropertyWrite("aname", this.aname, aname);
        this.aname = aname;
    }

    public String getAname() {
        beforePropertyRead("aname");
        return this.aname;
    }

    public void setAuid(String auid) {
        beforePropertyWrite("auid", this.auid, auid);
        this.auid = auid;
    }

    public String getAuid() {
        beforePropertyRead("auid");
        return this.auid;
    }

    public void addToCoreOperats(CoreOperat obj) {
        addToManyTarget("coreOperats", obj, true);
    }

    public void removeFromCoreOperats(CoreOperat obj) {
        removeToManyTarget("coreOperats", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<CoreOperat> getCoreOperats() {
        return (List<CoreOperat>)readProperty("coreOperats");
    }

    public void addToCoreOrganisationUsers(CoreOrganisationUser obj) {
        addToManyTarget("coreOrganisationUsers", obj, true);
    }

    public void removeFromCoreOrganisationUsers(CoreOrganisationUser obj) {
        removeToManyTarget("coreOrganisationUsers", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<CoreOrganisationUser> getCoreOrganisationUsers() {
        return (List<CoreOrganisationUser>)readProperty("coreOrganisationUsers");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "aname":
                return this.aname;
            case "auid":
                return this.auid;
            case "coreOperats":
                return this.coreOperats;
            case "coreOrganisationUsers":
                return this.coreOrganisationUsers;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "aname":
                this.aname = (String)val;
                break;
            case "auid":
                this.auid = (String)val;
                break;
            case "coreOperats":
                this.coreOperats = val;
                break;
            case "coreOrganisationUsers":
                this.coreOrganisationUsers = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.aname);
        out.writeObject(this.auid);
        out.writeObject(this.coreOperats);
        out.writeObject(this.coreOrganisationUsers);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.aname = (String)in.readObject();
        this.auid = (String)in.readObject();
        this.coreOperats = in.readObject();
        this.coreOrganisationUsers = in.readObject();
    }

}
